// Spoiler: Tut nicht ganz (:

let LEVEL = [
    {
        name: "demoLevel",
        data: [
            { x: 2, y: 3, material: 'grass', solid: true, interactive: false},
            { x: 3, y: 4, material: 'grass', solid: true, interactive: false},
            { x: 4, y: 4, material: 'grass', solid: true, interactive: false},
            { x: 5, y: 4, material: 'grass', solid: true, interactive: false},
            { x: 6, y: 5, material: 'grass', solid: true, interactive: false},
            { x: 7, y: 4, material: 'grass', solid: true, interactive: false},
            { x: 8, y: 4, material: 'grass', solid: true, interactive: false},
            { x: 9, y: 3, material: 'grass', solid: true, interactive: false}

        ]
    },

    {
        name: 'serverraum',
        data: [
        {x:0, y:0, material: 'SSF', solid: true, interactive: false},
        {x:0, y:1, material: 'SSU', solid: true, interactive: false},
        {x:0, y:2, material: 'SSU', solid: true, interactive: false},
        {x:0, y:3, material: 'SSU', solid: true, interactive: false},
        {x:0, y:4, material: 'SSU', solid: true, interactive: false},
        {x:0, y:5, material: 'SSU', solid: true, interactive: false},
        {x:0, y:6, material: 'SSU', solid: true, interactive: false},
        {x:0, y:7, material: 'SSU', solid: true, interactive: false},
        {x:0, y:8, material: 'SSU', solid: true, interactive: false},
        {x:0, y:9, material: 'SSU', solid: true, interactive: false},
        {x:0, y:10, material: 'SSU', solid: true, interactive: false},
        {x:0, y:11, material: 'SSU', solid: true, interactive: false},
        {x:0, y:13, material: 'SSU', solid: true, interactive: false},
        {x:0, y:14, material: 'SSU', solid: true, interactive: false},
    
        {x:1, y:0, material: 'SSL', solid: true, interactive: false},
        {x:1, y:5, material: 'SSM', solid: true, interactive: false},
       
        {x:2, y:0, material: 'SSF', solid: true, interactive: false},
        {x:2, y:1, material: 'SSF', solid: true, interactive: false},
        {x:2, y:3, material: 'SSD', solid: true, interactive: false},
        {x:2, y:5, material: 'SSM', solid: true, interactive: false},
        {x:2, y:7, material: 'SSD', solid: true, interactive: false},
        {x:2, y:8, material: 'SSD', solid: true, interactive: false},
        {x:2, y:9, material: 'SSD', solid: true, interactive: false},
        {x:2, y:10, material: 'SSD', solid: true, interactive: false},
        {x:2, y:12, material: 'SSD', solid: true, interactive: false},
        {x:2, y:11, material: 'SSD', solid: true, interactive: false},
        {x:2, y:14, material: 'SSR', solid: true, interactive: false},
    
        {x:3, y:3, material: 'SSM', solid: true, interactive: false},
        {x:3, y:5, material: 'SSU', solid: true, interactive: false},
        {x:3, y:7, material: 'SSM', solid: true, interactive: false},
        {x:3, y:14, material: 'SSR', solid: true, interactive: false},
    
        {x:4, y:1, material: 'SSD', solid: true, interactive: false},
        {x:4, y:3, material: 'SSM', solid: true, interactive: false},
        {x:4, y:7, material: 'SSM', solid: true, interactive: false},
        {x:4, y:9, material: 'SSR', solid: true, interactive: false},
        {x:4, y:10, material: 'SSF', solid: true, interactive: false},
        {x:4, y:14, material: 'SSR', solid: true, interactive: false},
    
        {x:5, y:1, material: 'SSF', solid: true, interactive: false},
        {x:5, y:3, material: 'SSU', solid: true, interactive: false},
        {x:5, y:5, material: 'SSF', solid: true, interactive: false},
        {x:5, y:6, material: 'SSF', solid: true, interactive: false},
        {x:5, y:7, material: 'SSF', solid: true, interactive: false},
        {x:5, y:10, material: 'SSF', solid: true, interactive: false},
        {x:5, y:12, material: 'SSF', solid: true, interactive: false},
        {x:5, y:13, material: 'SSF', solid: true, interactive: false},
        {x:5, y:14, material: 'SSU', solid: true, interactive: false},
    
        {x:6, y:1, material: 'SSF', solid: true, interactive: false},
        {x:6, y:5, material: 'SSF', solid: true, interactive: false},
        {x:6, y:7, material: 'SSR', solid: true, interactive: false},
        {x:6, y:8, material: 'SSF', solid: true, interactive: false},
        {x:6, y:9, material: 'SSF', solid: true, interactive: false},
        {x:6, y:10, material: 'SSF', solid: true, interactive: false},
        {x:6, y:12, material: 'SSF', solid: true, interactive: false},
        {x:6, y:13, material: 'SSF', solid: true, interactive: false},
    
        {x:7, y:1, material: 'SSF', solid: true, interactive: false},
        {x:7, y:2, material: 'SSD', solid: true, interactive: false},
        {x:7, y:3, material: 'SSD', solid: true, interactive: false},
        {x:7, y:4, material: 'SSD', solid: true, interactive: false},
        {x:7, y:5, material: 'SSF', solid: true, interactive: false},
        {x:7, y:12, material: 'SSM', solid: true, interactive: false},
       
        {x:8, y:1, material: 'SSM', solid: true, interactive: false},
        {x:8, y:6, material: 'SSF', solid: true, interactive: false},
        {x:8, y:7, material: 'SSF', solid: true, interactive: false},
        {x:8, y:8, material: 'SSF', solid: true, interactive: false},
        {x:8, y:9, material: 'SSF', solid: true, interactive: false},
        {x:8, y:11, material: 'SSF', solid: true, interactive: false},
        {x:8, y:12, material: 'SSF', solid: true, interactive: false},
        {x:8, y:14, material: 'SSR', solid: true, interactive: false},
    
        {x:9, y:1, material: 'SSM', solid: true, interactive: false},
        {x:9, y:3, material: 'SSF', solid: true, interactive: false},
        {x:9, y:4, material: 'SSF', solid: true, interactive: false},
        {x:9, y:5, material: 'SSF', solid: true, interactive: false},
        {x:9, y:6, material: 'SSF', solid: true, interactive: false},
        {x:9, y:7, material: 'SSF', solid: true, interactive: false},
        {x:9, y:8, material: 'SSL', solid: true, interactive: false},
        {x:9, y:11, material: 'SSF', solid: true, interactive: false},
        {x:9, y:12, material: 'SSF', solid: true, interactive: false},
        {x:9, y:13, material: 'SSL', solid: true, interactive: false},
    
        {x:10, y:11, material: 'SSF', solid: true, interactive: false},
        {x:10, y:1, material: 'SSM', solid: true, interactive: false},
        {x:10, y:3, material: 'SSF', solid: true, interactive: false},
        {x:10, y:4, material: 'SSF', solid: true, interactive: false},
        {x:10, y:5, material: 'SSF', solid: true, interactive: false},
        {x:10, y:7, material: 'SSF', solid: true, interactive: false},
        {x:10, y:8, material: 'SSL', solid: true, interactive: false},
        {x:10, y:13, material: 'SSF', solid: true, interactive: false},
    
        {x:11, y:1, material: 'SSM', solid: true, interactive: false},
        {x:11, y:3, material: 'SSM', solid: true, interactive: false},
        {x:11, y:13, material: 'SSF', solid: true, interactive: false},
        {x:11, y:14, material: 'SSF', solid: true, interactive: false},
    
        {x:12, y:1, material: 'SSU', solid: true, interactive: false},
        {x:12, y:3, material: 'SSM', solid: true, interactive: false},
        {x:12, y:5, material: 'SSR', solid: true, interactive: false},
        {x:12, y:6, material: 'SSF', solid: true, interactive: false},
        {x:12, y:7, material: 'SSF', solid: true, interactive: false},
        {x:12, y:10, material: 'SSF', solid: true, interactive: false},
        {x:12, y:9, material: 'SSF', solid: true, interactive: false},
        {x:12, y:10, material: 'SSF', solid: true, interactive: false},
        {x:12, y:12, material: 'SSF', solid: true, interactive: false},
        {x:12, y:13, material: 'SSF', solid: true, interactive: false},
        {x:12, y:14, material: 'SSF', solid: true, interactive: false},
        {x:12, y:11, material: 'SSF', solid: true, interactive: false},
    
        {x:13, y:3, material: 'SSM', solid: true, interactive: false},
        {x:13, y:12, material: 'SSR', solid: true, interactive: false},
        {x:13, y:13, material: 'SSL', solid: true, interactive: false},
    
        {x:14, y:1, material: 'SSR', solid: true, interactive: false},
        {x:14, y:2, material: 'SSF', solid: true, interactive: false},
        {x:14, y:3, material: 'SSF', solid: true, interactive: false},
        {x:14, y:4, material: 'SSF', solid: true, interactive: false},
        {x:14, y:5, material: 'SSF', solid: true, interactive: false},
        {x:14, y:6, material: 'SSF', solid: true, interactive: false},
        {x:14, y:9, material: 'SSR', solid: true, interactive: false},
        {x:14, y:10, material: 'SSL', solid: true, interactive: false},
        {x:14, y:13, material: 'SSM', solid: true, interactive: false},
        
        {x:15, y:11, material: 'SSL', solid: true, interactive: false},
        {x:15, y:5, material: 'SSR', solid: true, interactive: false},
        {x:15, y:6, material: 'SSL', solid: true, interactive: false},
        {x:15, y:9, material: 'SSR', solid: true, interactive: false},
        {x:15, y:10, material: 'SSF', solid: true, interactive: false},
        {x:15, y:13, material: 'SSL', solid: true, interactive: false},
    
        {x:16, y:0, material: 'SSF', solid: true, interactive: false},
        {x:16, y:1, material: 'SSF', solid: true, interactive: false},
        {x:16, y:11, material: 'SSM', solid: true, interactive: false},
        {x:16, y:3, material: 'SSL', solid: true, interactive: false},
        {x:16, y:4, material: 'SSR', solid: true, interactive: false},
        {x:16, y:5, material: 'SSF', solid: true, interactive: false},
        {x:16, y:6, material: 'SSF', solid: true, interactive: false},
        {x:16, y:7, material: 'SSL', solid: true, interactive: false},
    
        {x:17, y:0, material: 'SSF', solid: true, interactive: false},
        {x:17, y:1, material: 'SSF', solid: true, interactive: false},
        {x:17, y:2, material: 'SSL', solid: true, interactive: false},
        {x:17, y:11, material: 'SSR', solid: true, interactive: false},
        {x:17, y:9, material: 'SSF', solid: true, interactive: false},
        {x:17, y:10, material: 'SSF', solid: true, interactive: false},
        {x:17, y:12, material: 'SSF', solid: true, interactive: false},
        {x:17, y:13, material: 'SSL', solid: true, interactive: false},

        {x:18, y:0, material: 'SSL', solid: true, interactive: false},
        {x:18, y:6, material: 'SSR', solid: true, interactive: false},
        {x:18, y:7, material: 'SSL', solid: true, interactive: false},
        {x:18, y:10, material: 'SSM', solid: true, interactive: false},

        {x:19, y:0, material: 'SSF', solid: true, interactive: false},
        {x:19, y:1, material: 'SSD', solid: true, interactive: false},
        {x:19, y:2, material: 'SSD', solid: true, interactive: false},
        {x:19, y:3, material: 'SSD', solid: true, interactive: false},
        {x:19, y:4, material: 'SSD', solid: true, interactive: false},
        {x:19, y:5, material: 'SSD', solid: true, interactive: false},
        {x:19, y:6, material: 'SSF', solid: true, interactive: false},
        {x:19, y:7, material: 'SSF', solid: true, interactive: false},
        {x:19, y:8, material: 'SSD', solid: true, interactive: false},
        {x:19, y:9, material: 'SSD', solid: true, interactive: false},
        {x:19, y:10, material: 'SSF', solid: true, interactive: false},
        {x:19, y:11, material: 'SSD', solid: true, interactive: false},
        {x:19, y:12, material: 'SSD', solid: true, interactive: false},
        {x:19, y:13, material: 'SSD', solid: true, interactive: false},
        {x:19, y:14, material: 'SSD', solid: true, interactive: false},

        ]
    }


]