// Spoiler: Tut nicht ganz (:

let LEVEL = [
  {
    name: 'foyer',
    start_x: 10,
    start_y: 14,
    data: [
      {x:19, y:7, material: 'door', solid: false, interactive: true, interaction: "teleport_serverraum"}, //serverrraum
      {x:12, y:0, material: 'door', solid: false, interactive: true, interaction: "teleport_office"}, //eigenes büro
      {x:3, y:0, material: 'door', solid: false, interactive: true, interaction: "teleport_ceo"}, //aufzug ceo
      {x:0, y:7, material: 'door', solid: false, interactive: true, interaction: "teleport_cafeteria"}, //cafeteria
    /*{x:10, y:0, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:1, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:2, material: 'CRDR', solid: false, interactive: false},
    {x:10, y:3, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:4, material: 'CRDR', solid: false, interactive: false},
    {x:10, y:5, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:6, material: 'DESK', solid: true, interactive: false},
    {x:10, y:7, material: 'DESK', solid: true, interactive: false},
    {x:10, y:8, material: 'DESK', solid: true, interactive: false},
    {x:10, y:9, material: 'DESK', solid: true, interactive: false},
    {x:10, y:10, material: 'DESK', solid: true, interactive: false},
    {x:10, y:11, material: 'DESK', solid: true, interactive: false},
    {x:10, y:12, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:13, material: 'CRDR', solid: true, interactive: false},
    {x:10, y:14, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:15, material: 'CRDR', solid: true, interactive: false},
    {x:10, y:16, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:17, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:18, material: 'SPRU', solid: true, interactive: false},
    {x:10, y:19, material: 'SPRU', solid: true, interactive: false},
    

    {x:12, y:7, material: 'DPPH', solid: false, interactive: false},
    {x:12, y:10, material: 'DPPH', solid: false, interactive: false},

    {x:14, y:7, material: 'FPKF', solid: true, interactive: false},
    {x:14, y:10, material: 'FPKF', solid: true, interactive: false}  */

    ]
},

{ 
  name: 'kaffeeecke',
  start_x: 10,
  start_y: 14,
  data: [
  {x:0, y:0, material: 'KEW', solid: true, interactive: false},
  {x:0, y:1, material: 'KEW', solid: true, interactive: false},
  {x:0, y:2, material: 'KEW', solid: true, interactive: false},
  {x:0, y:3, material: 'KEW', solid: true, interactive: false},
  {x:0, y:4, material: 'KEW', solid: true, interactive: false},
  {x:0, y:5, material: 'KEW', solid: true, interactive: false},
  {x:0, y:6, material: 'KEW', solid: true, interactive: false},
  {x:0, y:7, material: 'KEW', solid: true, interactive: false},
  {x:0, y:8, material: 'KEW', solid: true, interactive: false},
  {x:0, y:9, material: 'KEW', solid: true, interactive: false},
  {x:0, y:10, material: 'KEW', solid: true, interactive: false},
  {x:0, y:11, material: 'KEW', solid: true, interactive: false},
  {x:0, y:12, material: 'KEW', solid: true, interactive: false},
  {x:0, y:13, material: 'KEW', solid: true, interactive: false},
  {x:0, y:14, material: 'KEW', solid: true, interactive: false},
  {x:0, y:15, material: 'KEW', solid: true, interactive: false},
  {x:0, y:16, material: 'KEW', solid: true, interactive: false},
  {x:0, y:17, material: 'KEW', solid: true, interactive: false},
  {x:0, y:18, material: 'KEW', solid: true, interactive: false},
  {x:0, y:19, material: 'KEW', solid: true, interactive: false},

  {x:1, y:0, material: 'KEW', solid: true, interactive: false},
  {x:1, y:2, material: 'KEW', solid: true, interactive: false},
  {x:1, y:4, material: 'KEW', solid: true, interactive: false},
  {x:1, y:5, material: 'KEW', solid: true, interactive: false},
  {x:1, y:6, material: 'KEW', solid: true, interactive: false},
  {x:1, y:7, material: 'KEW', solid: true, interactive: false},
  {x:1, y:12, material: 'KEW', solid: true, interactive: false},
  {x:1, y:14, material: 'KEW', solid: true, interactive: false},
  {x:1, y:15, material: 'KEW', solid: true, interactive: false},
  {x:1, y:16, material: 'KEW', solid: true, interactive: false},
  {x:1, y:19, material: 'KEW', solid: true, interactive: false},

  {x:2, y:0, material: 'KEW', solid: true, interactive: false},
  {x:2, y:2, material: 'KEW', solid: true, interactive: false},
  {x:2, y:7, material: 'KEW', solid: true, interactive: false},
  {x:2, y:8, material: 'KEW', solid: true, interactive: false},
  {x:2, y:9, material: 'KEW', solid: true, interactive: false},
  {x:2, y:10, material: 'KEW', solid: true, interactive: false},
  {x:2, y:12, material: 'KEW', solid: true, interactive: false},
  {x:2, y:14, material: 'KEW', solid: true, interactive: false},
  {x:2, y:15, material: 'KEW', solid: true, interactive: false},
  {x:2, y:16, material: 'KEW', solid: true, interactive: false},
  {x:2, y:19, material: 'KEW', solid: true, interactive: false},

  {x:3, y:0, material: 'KEW', solid: true, interactive: false},
  {x:3, y:2, material: 'KEW', solid: true, interactive: false},
  {x:3, y:3, material: 'KEW', solid: true, interactive: false},
  {x:3, y:4, material: 'KEW', solid: true, interactive: false},
  {x:3, y:5, material: 'KEW', solid: true, interactive: false},
  {x:3, y:12, material: 'KEW', solid: true, interactive: false},
  {x:3, y:19, material: 'KEW', solid: true, interactive: false},

  {x:4, y:0, material: 'KEW', solid: true, interactive: false},
  {x:4, y:5, material: 'KEW', solid: true, interactive: false},
  {x:4, y:7, material: 'KEW', solid: true, interactive: false},
  {x:4, y:8, material: 'KEW', solid: true, interactive: false},
  {x:4, y:10, material: 'KEW', solid: true, interactive: false},
  {x:4, y:12, material: 'KEW', solid: true, interactive: false},
  {x:4, y:14, material: 'KEW', solid: true, interactive: false},
  {x:4, y:15, material: 'KEW', solid: true, interactive: false},
  {x:4, y:16, material: 'KEW', solid: true, interactive: false},
  {x:4, y:17, material: 'KEW', solid: true, interactive: false},
  {x:4, y:18, material: 'KEW', solid: true, interactive: false},
  {x:4, y:19, material: 'KEW', solid: true, interactive: false},

  {x:5, y:0, material: 'KEW', solid: true, interactive: false},
  {x:5, y:1, material: 'KEW', solid: true, interactive: false},
  {x:5, y:4, material: 'KEW', solid: true, interactive: false},
  {x:5, y:5, material: 'KEW', solid: true, interactive: false},
  {x:5, y:8, material: 'KEW', solid: true, interactive: false},
  {x:5, y:10, material: 'KEW', solid: true, interactive: false},
  {x:5, y:12, material: 'KEW', solid: true, interactive: false},

  {x:6, y:0, material: 'KEW', solid: true, interactive: false},
  {x:6, y:7, material: 'KEW', solid: true, interactive: false},
  {x:6, y:8, material: 'KEW', solid: true, interactive: false},
  {x:6, y:10, material: 'KEW', solid: true, interactive: false},
  {x:6, y:11, material: 'KEW', solid: true, interactive: false},
  {x:6, y:12, material: 'KEW', solid: true, interactive: false},
  {x:6, y:13, material: 'KEW', solid: true, interactive: false},
  {x:6, y:14, material: 'KEW', solid: true, interactive: false},
  {x:6, y:15, material: 'KEW', solid: true, interactive: false},
  {x:6, y:19, material: 'KEW', solid: true, interactive: false},
  {x:6, y:17, material: 'KEW', solid: true, interactive: false},
  {x:6, y:18, material: 'KEW', solid: true, interactive: false},

  {x:7, y:0, material: 'KEW', solid: true, interactive: false},
  {x:7, y:1, material: 'KEW', solid: true, interactive: false},
  {x:7, y:2, material: 'KEW', solid: true, interactive: false},
  {x:7, y:3, material: 'KEW', solid: true, interactive: false},
  {x:7, y:4, material: 'KEW', solid: true, interactive: false},
  {x:7, y:5, material: 'KEW', solid: true, interactive: false},
  {x:7, y:6, material: 'KEW', solid: true, interactive: false},
  {x:7, y:7, material: 'KEW', solid: true, interactive: false},
  {x:7, y:17, material: 'KEW', solid: true, interactive: false},
  {x:7, y:19, material: 'KEW', solid: true, interactive: false},

  {x:8, y:0, material: 'KEW', solid: true, interactive: false},
  {x:8, y:2, material: 'KEW', solid: true, interactive: false},
  {x:8, y:3, material: 'KEW', solid: true, interactive: false},
  {x:8, y:4, material: 'KEW', solid: true, interactive: false},
  {x:8, y:5, material: 'KEW', solid: true, interactive: false},
  {x:8, y:6, material: 'KEW', solid: true, interactive: false},
  {x:8, y:7, material: 'KEW', solid: true, interactive: false},
  {x:8, y:9, material: 'KEW', solid: true, interactive: false},
  {x:8, y:10, material: 'KEW', solid: true, interactive: false},
  {x:8, y:11, material: 'KEW', solid: true, interactive: false},
  {x:8, y:12, material: 'KEW', solid: true, interactive: false},
  {x:8, y:13, material: 'KEW', solid: true, interactive: false},
  {x:8, y:15, material: 'KEW', solid: true, interactive: false},
  {x:8, y:17, material: 'KEW', solid: true, interactive: false},
  {x:8, y:19, material: 'KEW', solid: true, interactive: false},

  {x:9, y:2, material: 'KEW', solid: true, interactive: false},
  {x:9, y:7, material: 'KEW', solid: true, interactive: false},
  {x:9, y:9, material: 'KEW', solid: true, interactive: false},
  {x:9, y:13, material: 'KEW', solid: true, interactive: false},
  {x:9, y:15, material: 'KEW', solid: true, interactive: false},
  {x:9, y:17, material: 'KEW', solid: true, interactive: false},
  {x:9, y:19, material: 'KEW', solid: true, interactive: false},

  {x:10, y:0, material: 'KEW', solid: true, interactive: false},
  {x:10, y:4, material: 'KEW', solid: true, interactive: false},
  {x:10, y:5, material: 'KEW', solid: true, interactive: false},
  {x:10, y:7, material: 'KEW', solid: true, interactive: false},
  {x:10, y:9, material: 'KEW', solid: true, interactive: false},
  {x:10, y:17, material: 'KEW', solid: true, interactive: false},
  {x:10, y:19, material: 'KEW', solid: true, interactive: false},

  {x:11, y:0, material: 'KEW', solid: true, interactive: false},
  {x:11, y:1, material: 'KEW', solid: true, interactive: false},
  {x:11, y:2, material: 'KEW', solid: true, interactive: false},
  {x:11, y:3, material: 'KEW', solid: true, interactive: false},
  {x:11, y:4, material: 'KEW', solid: true, interactive: false},
  {x:11, y:7, material: 'KEW', solid: true, interactive: true},
  {x:11, y:11, material: 'KEW', solid: true, interactive: true},
  {x:11, y:13, material: 'KEW', solid: true, interactive: false},
  {x:11, y:17, material: 'KEW', solid: true, interactive: false},
  {x:11, y:18, material: 'KEW', solid: true, interactive: false},
  {x:11, y:19, material: 'KEW', solid: true, interactive: false},

  {x:12, y:0, material: 'KEW', solid: true, interactive: false},
  {x:12, y:2, material: 'KEKM', solid: true, interactive: false},
  {x:12, y:3, material: 'KEW', solid: true, interactive: false},
  {x:12, y:4, material: 'KEW', solid: true, interactive: false},
  {x:12, y:5, material: 'KEW', solid: true, interactive: false},
  {x:12, y:7, material: 'KEW', solid: true, interactive: false},
  {x:12, y:8, material: 'KEW', solid: true, interactive: false},
  {x:12, y:9, material: 'KEW', solid: true, interactive: false},
  {x:12, y:10, material: 'KEW', solid: true, interactive: false},
  {x:12, y:11, material: 'KEW', solid: true, interactive: false},
  {x:12, y:13, material: 'KEW', solid: true, interactive: false},
  {x:12, y:14, material: 'KEW', solid: true, interactive: false},
  {x:12, y:19, material: 'KEW', solid: true, interactive: false},

  {x:13, y:0, material: 'KEW', solid: true, interactive: false},
  {x:13, y:13, material: 'KEW', solid: true, interactive: false},
  {x:13, y:14, material: 'KEW', solid: true, interactive: false},
  {x:13, y:15, material: 'KEW', solid: true, interactive: false},
  {x:13, y:16, material: 'KEW', solid: true, interactive: false},
  {x:13, y:17, material: 'KEW', solid: true, interactive: false},
  {x:13, y:18, material: 'KEW', solid: true, interactive: false},
  {x:13, y:19, material: 'KEW', solid: true, interactive: false},

  {x:14, y:0, material: 'KEW', solid: true, interactive: false},
  {x:14, y:1, material: 'KEW', solid: true, interactive: false},
  {x:14, y:2, material: 'KEW', solid: true, interactive: false},
  {x:14, y:3, material: 'KEW', solid: true, interactive: false},
  {x:14, y:4, material: 'KEW', solid: true, interactive: false},
  {x:14, y:5, material: 'KEW', solid: true, interactive: false},
  {x:14, y:6, material: 'KEW', solid: true, interactive: false},
  {x:14, y:7, material: 'KEW', solid: true, interactive: false},
  {x:14, y:8, material: 'KEW', solid: true, interactive: false},
  {x:14, y:9, material: 'KEW', solid: true, interactive: false},
  {x:14, y:10, material: 'KEW', solid: true, interactive: false},
  {x:14, y:11, material: 'KEW', solid: true, interactive: false},
  {x:14, y:12, material: 'KEW', solid: true, interactive: false},
  {x:14, y:13, material: 'KEW', solid: true, interactive: false},
  {x:14, y:14, material: 'KEW', solid: true, interactive: false},
  {x:14, y:15, material: 'KEW', solid: true, interactive: false},
  {x:14, y:16, material: 'KEW', solid: true, interactive: false},
  {x:14, y:17, material: 'KEW', solid: true, interactive: false},
  {x:14, y:18, material: 'KEW', solid: true, interactive: false},
  {x:14, y:19, material: 'KEW', solid: true, interactive: false},
  
]
},






  {
    name: 'serverraum',
    start_x: 1,
    start_y: 3,
    data: [
      {        x: 0,        y: 3,        material: 'door',        solid: false,        interactive: true,        interaction: 'teleport_foyer'      },
      {x: 0, y: 0, material: 'SSF', solid: true, interactive: false},
      {x: 2, y: 0, material: 'SSF', solid: true, interactive: false},
      {        x: 3,        y: 0,        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 4,
        y: 0,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 0,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 8,
        y: 0,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 0,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 10,
        y: 0,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 11,
        y: 0,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 0,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 0,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 6,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 11,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 13,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 15,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 17,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 1,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 6,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 7,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 8,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 13,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 17,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 2,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 8,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 10,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 15,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 16,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 17,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 3,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 4,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 6,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 10,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 15,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 17,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 18,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 4,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 4,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 6,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 8,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 15,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 17,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 5,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 6,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 6,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 6,
        y: 6,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 8,
        y: 6,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 6,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 6,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      
      {
        x: 0,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 3,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 4,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 6,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 8,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 10,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 16,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 18,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 7,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 8,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 15,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 16,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 18,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 8,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 1,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 3,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 6,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 7,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 10,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 15,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 16,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 9,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 10,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 7,
        y: 10,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 10,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 10,
        y: 10,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 10,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 16,
        y: 10,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 10,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 3,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 4,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 7,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 10,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 11,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 13,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 11,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 12,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 7,
        y: 12,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 12,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 16,
        y: 12,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 17,
        y: 12,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 12,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 4,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 5,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 6,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 7,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 8,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 9,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 10,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 11,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 12,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 14,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 16,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 17,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 13,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 0,
        y: 14,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 1,
        y: 14,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 2,
        y: 14,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 16,
        y: 14,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 17,
        y: 14,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 18,
        y: 14,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
      {
        x: 19,
        y: 14,
        material: 'SSF',
        solid: true,
        interactive: false,
      },
    ],
  },
];
